apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.app.name }}
  http:
    - route:
        - destination:
            host: {{ .Values.app.name }}
            port:
              number: {{ .Values.app.service.port }}
      retries:
        attempts: 3
        perTryTimeout: 2s
      timeout: 10s
      fault:
        delay:
          percentage:
            value: 0.1
          fixedDelay: 5s
      corsPolicy:
        allowOrigins:
          - exact: "*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - content-type
          - authorization
        maxAge: 24h 